---

- name: install packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items: "{{ redis_packages }}"

- name: config
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart redis

- name: service start
  service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: yes
